### ISSUE TITLE
LoadAuthorize() can't get value

### ISSUE THREAD

**Issue by lewgun** [ory-am/osin-storage#8]
postgres.go L262:
   ...
   authorize, err := s.LoadAuthorize(authorizeCode)
  ...

but osin/access.go L472
...
// remove authorization token
if ret.AuthorizeData != nil {
	w.Storage.RemoveAuthorize(ret.AuthorizeData.Code)
}
...

so when LoadAcess it's failed, is there something wrong  or i ignore something?

**Comment by arekkas** [comment]
Hey this looks like a bug, thanks for reporting. I'll look at it in detail in an hour.

**Comment by arekkas** [comment]
Does #9 resolve your issues?

**Comment by lewgun** [comment]
i will check it tomorrow, and let u know, it's 10PM in china , thx

**Comment by arekkas** [comment]
sure :)

**Comment by lewgun** [comment]
it's works, thx

**Comment by arekkas** [comment]
ok cool, I'll merge it :)
